Lesson4
ozoncp/ocp-resume-api pull request #1
Opened 2021-06-02 14:22 UTC by NewDenis

4 homework with empty tests

2021-06-02 20:46 UTC, xmikasax requested changes

2021-06-02 20:46 UTC, xmikasax commented on internal/flusher/flusher_test.go
> +	Context("got empty arrays", func() {
Не хватает тестов на все остальное :)

2021-06-02 22:30 UTC, NewDenis commented on internal/flusher/flusher_test.go
> +	Context("got empty arrays", func() {
Добавил :) понимаю, что не оптимально, но у меня сегодня была защита диплома по нейронкам и тяжко думать :)

2021-06-03 08:50 UTC, xmikasax approved these changes

2021-06-03 08:50 UTC, xmikasax commented on internal/flusher/flusher_test.go
> +			It("result", func() {
Сюда стоит написать что-то осмысленное. Что именно должно произойти в описанном выше контексте

2021-06-03 14:05 UTC, xmikasax approved these changes
Ок

2021-06-03 15:07 UTC, merged